Feature/tda 43 task createion dialog
blerinebee/todo-app-frontend pull request #4
Opened 2022-12-13 09:43 UTC by shawn-lacarta

2022-12-13 10:03 UTC, shawn-lacarta commented
noch nicht approven, muss noch validation hinzufügen

2022-12-13 10:23 UTC, alishakhalid commented on todoapp-fe/src/UI/styles/TaskCreationDialog.scss
> +}
Farbe von Button von blau auf grün ändern

2022-12-13 10:25 UTC, alishakhalid commented on todoapp-fe/src/UI/organisms/TaskCreationDialog.tsx
> +            className='hello'
className von hello auf etwas anderes ändern.

2022-12-13 10:25 UTC, alishakhalid commented on todoapp-fe/src/UI/organisms/TaskCreationDialog.tsx
> +          <Button onClick={handleClose} variant='outlined' sx={{backgroundColor: '#49B093', borderColor: '#49B093', color: 'white'}} className='buttons'>Create</Button>
Create zu Add ändern

2022-12-13 10:26 UTC, alishakhalid requested changes
Bitte alles anpassen :)

2022-12-19 21:39 UTC, alishakhalid approved these changes

2022-12-20 09:59 UTC, Milena-Blaser approved these changes

2022-12-20 09:59 UTC, Milena-Blaser commented on todoapp-fe/src/App.tsx
> +   <Typography>hello</Typography>
Bitte entfernen

2022-12-20 09:59 UTC, merged